spring:
  application.name: mystery-box-service
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat.options.model: gpt-4o-mini
    chat.observations:
      log-prompt: true
      log-completion: true
      include-error-logging: true
  mvc.apiversion:
    use.path-segment: 1
    supported: 1

server.port: 8081

management:
  endpoints.web.exposure.include: "*"
  endpoint.env.show-values: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name} # These tag appears in all metrics → Correlation with logs/traces
    distribution.percentiles-histogram:
      http.server.requests: true
      http.client.requests: true
  tracing.sampling.probability: 1.0
  otlp.metrics.export.step: 5s
  observations.annotations.enabled: true
  opentelemetry:
    tracing.export.otlp.endpoint: http://localhost:4318/v1/traces
    logging.export.otlp.endpoint: http://localhost:4318/v1/logs