apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: "Trace: ${__value.raw}"

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    jsonData:
      derivedFields:
        - name: trace_id
          matcherType: label
          matcherRegex: trace_id
          url: "$${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: 'View Trace'

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://127.0.0.1:3200
    version: 1
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [ { key: "service.name", value: "service_name" } ]
        queries:
          - name: 'Throughput'
            query: 'sum(rate(http_server_requests_milliseconds_count{$$__tags}[$$__rate_interval]))'
          - name: 'Latency'
            query: 'histogram_quantile(1.00, sum(rate(http_server_requests_milliseconds_bucket{$$__tags}[$$__rate_interval])) by (le))'
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
      traceToProfiles:
        datasourceUid: pyroscope
        profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
        customQuery: false
        query: 'method="${__span.tags.method}"'
  - name: Pyroscope
    uid: pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://127.0.0.1:4040