spring:
  application.name: order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  sql.init.mode: always

management:
  endpoints.web.exposure.include: "*"
  endpoint.env.show-values: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name} # These tag appears in all metrics → Correlation with logs/traces
    distribution.percentiles-histogram:
      http.server.requests: true
      http.client.requests: true
  tracing.sampling.probability: 1.0
  otlp.metrics.export.step: 5s
  observations.annotations.enabled: true
  opentelemetry:
    tracing.export.otlp.endpoint: http://localhost:4318/v1/traces
    logging.export.otlp.endpoint: http://localhost:4318/v1/logs

order:
  mystery-box-api-url: ${MYSTERY_BOX_SERVICE_URL:http://localhost:8081}/api
  products:
    - sku: MYSTERY_BOX
      name: Mystery Box
      cost: 49.99
      stock: 13
    - sku: RUBBER-DUCK
      name: Sentient Rubber Duck
      cost: 4.99
      stock: 42
    - sku: FOREVER-PEN
      name: Pen That Never Runs Out (It Does)
      cost: 9.99
      stock: 15
    - sku: ALARM-CLOCK
      name: Alarm Clock That Judges You
      cost: 19.99
      stock: 8
    - sku: UMBRELLA
      name: Umbrella That Inverts in Light Breeze
      cost: 7.49
      stock: 23